a = input("Digite: ")
print("Tipo primitivo: ",type(a))
print("Contem apenas espaços: ",a.isspace())
print("É um numero: ",a.isnumeric())
print("É alfabético: ",a.isalpha())
print("É alfanumeroco: ",a.isalnum())
print("Esta em maiusculas: ",a.isupper())
print("Esta em minusculas: ",a.islower())
print("Está capitalizada: ",a.istitle())
